// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddUserReq struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Roles    []string `json:"roles"`
}

type BaseResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type CaddyLogItem struct {
	ID        uint   `json:"id"`
	LogTime   string `json:"logTime"`
	Country   string `json:"country"`
	City      string `json:"city"`
	Host      string `json:"host"`
	Method    string `json:"method"`
	Uri       string `json:"uri"`
	Status    int    `json:"status"`
	Size      int64  `json:"size"`
	RemoteIP  string `json:"remoteIp"`
	ClientIP  string `json:"clientIp"`
	UserAgent string `json:"userAgent"`
}

type CaddyLogReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	Keyword  string `form:"keyword,optional"` // Search in host, uri, ip
}

type CaddyLogResp struct {
	List  []CaddyLogItem `json:"list"`
	Total int64          `json:"total"`
}

type IDReq struct {
	ID uint `path:"id"`
}

type IsRouteExistReq struct {
	RouteName string `form:"routeName"`
}

type LogSourceItem struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	Type      string `json:"type"`
	Enabled   bool   `json:"enabled"`
	CreatedAt string `json:"createdAt"`
}

type LogSourceListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=20"`
}

type LogSourceListResp struct {
	List  []LogSourceItem `json:"list"`
	Total int64           `json:"total"`
}

type LogSourceReq struct {
	Name string `json:"name"`
	Path string `json:"path"`
	Type string `json:"type,default=caddy"`
}

type LogSourceUpdateReq struct {
	ID      uint   `path:"id"`
	Name    string `json:"name,optional"`
	Path    string `json:"path,optional"`
	Enabled bool   `json:"enabled,optional"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type MenuRoute struct {
	Name      string      `json:"name"`
	Path      string      `json:"path"`
	Component string      `json:"component"`
	Meta      RouteMeta   `json:"meta"`
	Children  []MenuRoute `json:"children,omitempty"`
}

type RoleItem struct {
	ID          uint     `json:"id"`
	Name        string   `json:"name"`
	DisplayName string   `json:"displayName"`
	Description string   `json:"description"`
	Permissions []string `json:"permissions"`
	CreatedAt   string   `json:"createdAt"`
}

type RoleListResp struct {
	List []RoleItem `json:"list"`
}

type RouteMeta struct {
	Title      string   `json:"title"`
	I18nKey    string   `json:"i18nKey,omitempty"`
	Icon       string   `json:"icon,omitempty"`
	LocalIcon  string   `json:"localIcon,omitempty"`
	Order      int      `json:"order,omitempty"`
	HideInMenu bool     `json:"hideInMenu,omitempty"`
	Roles      []string `json:"roles,omitempty"`
}

type UpdateRolePermissionsReq struct {
	ID          uint     `path:"id"`
	Permissions []string `json:"permissions"`
}

type UpdateUserReq struct {
	ID       uint     `path:"id"`
	Password string   `json:"password,optional"`
	Roles    []string `json:"roles,optional"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserId   int64    `json:"userId"`
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
}

type UserItem struct {
	ID        uint     `json:"id"`
	Username  string   `json:"username"`
	Roles     []string `json:"roles"`
	Status    int      `json:"status"` // 1=启用, 0=禁用
	CreatedAt string   `json:"createdAt"`
}

type ToggleUserStatusReq struct {
	ID uint `path:"id"`
}

type UserListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	Username string `form:"username,optional"`
}

type UserListResp struct {
	List  []UserItem `json:"list"`
	Total int64      `json:"total"`
}

type UserRouteResp struct {
	Home   string      `json:"home"`
	Routes []MenuRoute `json:"routes"`
}
