// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddUserReq struct {
	Username string   `json:"username"`
	Password string   `json:"password"`
	Roles    []string `json:"roles"`
}

type BaseResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type CaddyConfigReq struct {
	ServerId uint `path:"serverId"`
}

type CaddyConfigResp struct {
	Config string `json:"config"`
}

type CaddyConfigUpdateReq struct {
	ServerId uint   `path:"serverId"`
	Config   string `json:"config"` // JSON string
}

type CaddyLogItem struct {
	ID        uint   `json:"id"`
	LogTime   string `json:"logTime"`
	Country   string `json:"country"`
	City      string `json:"city"`
	Host      string `json:"host"`
	Method    string `json:"method"`
	Uri       string `json:"uri"`
	Status    int    `json:"status"`
	Size      int64  `json:"size"`
	RemoteIP  string `json:"remoteIp"`
	ClientIP  string `json:"clientIp"`
	UserAgent string `json:"userAgent"`
}

type CaddyLogReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	Keyword  string `form:"keyword,optional"` // Search in host, uri, ip
}

type CaddyLogResp struct {
	List  []CaddyLogItem `json:"list"`
	Total int64          `json:"total"`
}

type CaddyServerItem struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Url       string `json:"url"`
	Type      string `json:"type"`
	CreatedAt string `json:"createdAt"`
}

type CaddyServerListResp struct {
	List []CaddyServerItem `json:"list"`
}

type CaddyServerReq struct {
	Name     string `json:"name"`
	Url      string `json:"url"`                // http://localhost:2019 or remote IP
	Token    string `json:"token,optional"`     // For remote auth if needed
	Type     string `json:"type,default=local"` // local | remote
	Username string `json:"username,optional"`
	Password string `json:"password,optional"`
}

type ChannelItem struct {
	ID          uint   `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Enabled     bool   `json:"enabled"`
	Config      string `json:"config"`
	Events      string `json:"events"`
	Description string `json:"description"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type ChannelListResp struct {
	List []ChannelItem `json:"list"`
}

type ChannelReq struct {
	Name        string `json:"name"`
	Type        string `json:"type"` // email, webhook, telegram
	Enabled     bool   `json:"enabled"`
	Config      string `json:"config"` // JSON string
	Events      string `json:"events"` // JSON string array ["*"]
	Description string `json:"description,optional"`
}

type ChannelUpdateReq struct {
	ID          uint   `path:"id"`
	Name        string `json:"name,optional"`
	Type        string `json:"type,optional"`
	Enabled     bool   `json:"enabled,optional"`
	Config      string `json:"config,optional"`
	Events      string `json:"events,optional"`
	Description string `json:"description,optional"`
}

type IDReq struct {
	ID uint `path:"id"`
}

type IsRouteExistReq struct {
	RouteName string `form:"routeName"`
}

type LogItem struct {
	ID         uint   `json:"id"`
	EventID    string `json:"eventId"`
	EventType  string `json:"eventType"`
	Title      string `json:"title"`
	Message    string `json:"message"`
	Level      string `json:"level"`
	ChannelID  uint   `json:"channelId"`
	RuleID     uint   `json:"ruleId"`
	Status     int    `json:"status"`
	Error      string `json:"error"`
	RetryCount int    `json:"retryCount"`
	SentAt     string `json:"sentAt"`
	CreatedAt  string `json:"createdAt"`
}

type LogListReq struct {
	Page      int  `form:"page,default=1"`
	PageSize  int  `form:"pageSize,default=20"`
	Status    int  `form:"status,optional"` // 0:pending, 1:sending, 2:success, 3:failed
	ChannelID uint `form:"channelId,optional"`
	RuleID    uint `form:"ruleId,optional"`
}

type LogListResp struct {
	List  []LogItem `json:"list"`
	Total int64     `json:"total"`
}

type LogSourceItem struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Path      string `json:"path"`
	Type      string `json:"type"`
	Enabled   bool   `json:"enabled"`
	CreatedAt string `json:"createdAt"`
}

type LogSourceListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"pageSize,default=20"`
}

type LogSourceListResp struct {
	List  []LogSourceItem `json:"list"`
	Total int64           `json:"total"`
}

type LogSourceReq struct {
	Name string `json:"name"`
	Path string `json:"path"`
	Type string `json:"type,default=caddy"`
}

type LogSourceUpdateReq struct {
	ID      uint   `path:"id"`
	Name    string `json:"name,optional"`
	Path    string `json:"path,optional"`
	Enabled bool   `json:"enabled,optional"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type MenuRoute struct {
	Name      string      `json:"name"`
	Path      string      `json:"path"`
	Component string      `json:"component"`
	Meta      RouteMeta   `json:"meta"`
	Children  []MenuRoute `json:"children,omitempty"`
}

type PreviewTemplateReq struct {
	Format  string `json:"format"`
	Content string `json:"content"`
	Data    string `json:"data,optional"` // JSON string of mock data
}

type PreviewTemplateResp struct {
	Content string `json:"content"`
}

type RoleItem struct {
	ID          uint     `json:"id"`
	Name        string   `json:"name"`
	DisplayName string   `json:"displayName"`
	Description string   `json:"description"`
	Permissions []string `json:"permissions"`
	CreatedAt   string   `json:"createdAt"`
}

type RoleListResp struct {
	List []RoleItem `json:"list"`
}

type RouteMeta struct {
	Title      string   `json:"title,optional"`
	I18nKey    string   `json:"i18nKey,omitempty"`
	Icon       string   `json:"icon,omitempty"`
	LocalIcon  string   `json:"localIcon,omitempty"`
	Order      int      `json:"order,omitempty"`
	HideInMenu bool     `json:"hideInMenu,omitempty"`
	Roles      []string `json:"roles,omitempty"`
}

type RuleItem struct {
	ID              uint    `json:"id"`
	Name            string  `json:"name"`
	Enabled         bool    `json:"enabled"`
	RuleType        string  `json:"ruleType"`
	EventType       string  `json:"eventType"`
	Condition       string  `json:"condition"`
	ChannelIDs      []int64 `json:"channelIds"`
	Template        string  `json:"template"`
	SilenceDuration int     `json:"silenceDuration"`
	Description     string  `json:"description"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
}

type RuleListResp struct {
	List []RuleItem `json:"list"`
}

type RuleReq struct {
	Name            string  `json:"name"`
	Enabled         bool    `json:"enabled"`
	RuleType        string  `json:"ruleType"` // threshold, frequency, pattern
	EventType       string  `json:"eventType"`
	Condition       string  `json:"condition"` // JSON string
	ChannelIDs      []int64 `json:"channelIds"`
	Template        string  `json:"template,optional"`
	SilenceDuration int     `json:"silenceDuration"` // seconds
	Description     string  `json:"description,optional"`
}

type RuleUpdateReq struct {
	ID              uint    `path:"id"`
	Name            string  `json:"name,optional"`
	Enabled         bool    `json:"enabled,optional"`
	RuleType        string  `json:"ruleType,optional"`
	EventType       string  `json:"eventType,optional"`
	Condition       string  `json:"condition,optional"`
	ChannelIDs      []int64 `json:"channelIds,optional"`
	Template        string  `json:"template,optional"`
	SilenceDuration int     `json:"silenceDuration,optional"`
	Description     string  `json:"description,optional"`
}

type TemplateItem struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Format    string `json:"format"`
	Content   string `json:"content"`
	Type      string `json:"type"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type TemplateListResp struct {
	List []TemplateItem `json:"list"`
}

type TemplateReq struct {
	Name    string `json:"name"`
	Format  string `json:"format"` // text, html, markdown, json
	Content string `json:"content"`
	Type    string `json:"type,default=user"` // system, user
}

type TemplateUpdateReq struct {
	ID      uint   `path:"id"`
	Name    string `json:"name,optional"`
	Format  string `json:"format,optional"`
	Content string `json:"content,optional"`
	Type    string `json:"type,optional"`
}

type TestChannelReq struct {
	ID uint `json:"id"`
}

type UpdateCaddyServerReq struct {
	ID       uint   `path:"id"`
	Name     string `json:"name,optional"`
	Url      string `json:"url,optional"`
	Token    string `json:"token,optional"`
	Type     string `json:"type,optional"`
	Username string `json:"username,optional"`
	Password string `json:"password,optional"`
}

type UpdateRolePermissionsReq struct {
	ID          uint     `path:"id"`
	Permissions []string `json:"permissions"`
}

type UpdateUserReq struct {
	ID       uint     `path:"id"`
	Password string   `json:"password,optional"`
	Roles    []string `json:"roles,optional"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserId   int64    `json:"userId"`
	Username string   `json:"username"`
	Roles    []string `json:"roles"`
}

type UserItem struct {
	ID        uint     `json:"id"`
	Username  string   `json:"username"`
	Roles     []string `json:"roles"`
	CreatedAt string   `json:"createdAt"`
}

type UserListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	Username string `form:"username,optional"`
}

type UserListResp struct {
	List  []UserItem `json:"list"`
	Total int64      `json:"total"`
}

type UserRouteResp struct {
	Home   string      `json:"home"`
	Routes []MenuRoute `json:"routes"`
}

type MenuItem struct {
	ID            uint       `json:"id"`
	Name          string     `json:"name"`
	Path          string     `json:"path"`
	Component     string     `json:"component"`
	Order         int        `json:"order"`
	Meta          RouteMeta  `json:"meta"`
	RequiredRoles []string   `json:"roles"`
	Children      []MenuItem `json:"children,omitempty"`
	CreatedAt     string     `json:"createdAt"`
}

type MenuListResp struct {
	List []MenuItem `json:"list"`
}

type CreateMenuReq struct {
	Name          string    `json:"name"`
	Path          string    `json:"path"`
	Component     string    `json:"component"`
	Order         int       `json:"order"`
	Meta          RouteMeta `json:"meta"`
	RequiredRoles []string  `json:"roles"`
	ParentID      uint      `json:"parentId,optional"`
}

type UpdateMenuReq struct {
	ID            uint      `path:"id" json:"id,optional"`
	Name          string    `json:"name"`
	Path          string    `json:"path"`
	Component     string    `json:"component"`
	Order         int       `json:"order"`
	Meta          RouteMeta `json:"meta"`
	RequiredRoles []string  `json:"roles"`
	ParentID      uint      `json:"parentId,optional"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}
