// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	auth "logflux/internal/handler/auth"
	log "logflux/internal/handler/log"
	"logflux/internal/handler/route"
	user "logflux/internal/handler/user"
	"logflux/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/caddy/logs",
				Handler: log.GetCaddyLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/source",
				Handler: log.AddLogSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/source",
				Handler: log.ListLogSourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/source/:id",
				Handler: log.UpdateLogSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/source/:id",
				Handler: log.DeleteLogSourceHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: user.GetUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: user.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/:id",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/route/getUserRoutes",
				Handler: route.GetUserRoutesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/route/getConstantRoutes",
				Handler: route.GetConstantRoutesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/route/isRouteExist",
				Handler: route.IsRouteExistHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
