// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	auth "logflux/internal/handler/auth"
	caddy "logflux/internal/handler/caddy"
	log "logflux/internal/handler/log"
	role "logflux/internal/handler/role"
	route "logflux/internal/handler/route"
	user "logflux/internal/handler/user"
	"logflux/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/logs/caddy",
				Handler: log.GetCaddyLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/source",
				Handler: log.AddLogSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/source",
				Handler: log.ListLogSourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/source/:id",
				Handler: log.UpdateLogSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/source/:id",
				Handler: log.DeleteLogSourceHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/role/:id/permissions",
				Handler: role.UpdateRolePermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/list",
				Handler: role.GetRoleListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/route/getUserRoutes",
				Handler: route.GetUserRoutesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/route/getConstantRoutes",
				Handler: route.GetConstantRoutesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/route/isRouteExist",
				Handler: route.IsRouteExistHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: user.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/:id",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/:id/status",
				Handler: user.ToggleUserStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: user.GetUserListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/caddy/server",
				Handler: caddy.GetCaddyServersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/caddy/server",
				Handler: caddy.AddCaddyServerHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/caddy/server/:id",
				Handler: caddy.UpdateCaddyServerHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/caddy/server/:id",
				Handler: caddy.DeleteCaddyServerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/caddy/server/:serverId/config",
				Handler: caddy.GetCaddyConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/caddy/server/:serverId/config",
				Handler: caddy.UpdateCaddyConfigHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
