// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	auth "logflux/internal/handler/auth"
	caddy "logflux/internal/handler/caddy"
	cron "logflux/internal/handler/cron"
	log "logflux/internal/handler/log"
	menu "logflux/internal/handler/menu"
	notification "logflux/internal/handler/notification"
	role "logflux/internal/handler/role"
	route "logflux/internal/handler/route"
	user "logflux/internal/handler/user"
	"logflux/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/caddy/server",
				Handler: caddy.GetCaddyServersHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/caddy/server",
				Handler: caddy.AddCaddyServerHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/caddy/server/:id",
				Handler: caddy.UpdateCaddyServerHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/caddy/server/:id",
				Handler: caddy.DeleteCaddyServerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/caddy/server/:serverId/config",
				Handler: caddy.GetCaddyConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/caddy/server/:serverId/config",
				Handler: caddy.UpdateCaddyConfigHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/cron/log",
				Handler: cron.GetCronLogListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cron/task",
				Handler: cron.GetCronTaskListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cron/task",
				Handler: cron.CreateCronTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/cron/task/:id",
				Handler: cron.UpdateCronTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/cron/task/:id",
				Handler: cron.DeleteCronTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cron/task/:id/trigger",
				Handler: cron.TriggerCronTaskHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/source",
				Handler: log.AddLogSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/source",
				Handler: log.ListLogSourcesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/source/:id",
				Handler: log.UpdateLogSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/source/:id",
				Handler: log.DeleteLogSourceHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/caddy/logs",
				Handler: log.GetCaddyLogsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/menu",
				Handler: menu.CreateMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/menu/:id",
				Handler: menu.UpdateMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/menu/:id",
				Handler: menu.DeleteMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/menu/list",
				Handler: menu.GetMenuListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/notification/channel",
				Handler: notification.GetChannelListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/channel",
				Handler: notification.CreateChannelHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/notification/channel/:id",
				Handler: notification.UpdateChannelHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/notification/channel/:id",
				Handler: notification.DeleteChannelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/channel/test",
				Handler: notification.TestChannelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notification/log",
				Handler: notification.GetNotificationLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/read/:id",
				Handler: notification.ReadNotificationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/read/all",
				Handler: notification.ReadAllNotificationsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notification/rule",
				Handler: notification.GetRuleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/rule",
				Handler: notification.CreateRuleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/notification/rule/:id",
				Handler: notification.UpdateRuleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/notification/rule/:id",
				Handler: notification.DeleteRuleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notification/template",
				Handler: notification.GetTemplateListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/template",
				Handler: notification.CreateTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/notification/template/:id",
				Handler: notification.UpdateTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/notification/template/:id",
				Handler: notification.DeleteTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notification/template/preview",
				Handler: notification.PreviewTemplateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notification/unread",
				Handler: notification.GetUnreadNotificationsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/role/:id/permissions",
				Handler: role.UpdateRolePermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/list",
				Handler: role.GetRoleListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/route/getUserRoutes",
				Handler: route.GetUserRoutesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/route/getConstantRoutes",
				Handler: route.GetConstantRoutesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/route/isRouteExist",
				Handler: route.IsRouteExistHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user",
				Handler: user.AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/:id",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/change_password",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: user.GetUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/preferences",
				Handler: user.UpdateUserPreferencesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
