/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'caddy',
    path: '/caddy',
    component: 'layout.base',
    meta: {
      title: 'caddy',
      i18nKey: 'route.caddy'
    },
    children: [
      {
        name: 'caddy_config',
        path: '/caddy/config',
        component: 'view.caddy_config',
        meta: {
          title: 'caddy_config',
          i18nKey: 'route.caddy_config'
        }
      },
      {
        name: 'caddy_log',
        path: '/caddy/log',
        component: 'view.caddy_log',
        meta: {
          title: 'caddy_log',
          i18nKey: 'route.caddy_log'
        }
      },
      {
        name: 'caddy_source',
        path: '/caddy/source',
        component: 'view.caddy_source',
        meta: {
          title: 'caddy_source',
          i18nKey: 'route.caddy_source'
        }
      },
      {
        name: 'caddy_system-log',
        path: '/caddy/system-log',
        component: 'view.caddy_system-log',
        meta: {
          title: 'caddy_system-log',
          i18nKey: 'route.caddy_system-log'
        }
      }
    ]
  },
  {
    name: 'cron',
    path: '/cron',
    component: 'layout.base$view.cron',
    meta: {
      title: 'cron',
      i18nKey: 'route.cron'
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage'
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user'
        }
      }
    ]
  },
  {
    name: 'notification',
    path: '/notification',
    component: 'layout.base',
    meta: {
      title: 'notification',
      i18nKey: 'route.notification'
    },
    children: [
      {
        name: 'notification_channel',
        path: '/notification/channel',
        component: 'view.notification_channel',
        meta: {
          title: 'notification_channel',
          i18nKey: 'route.notification_channel'
        }
      },
      {
        name: 'notification_log',
        path: '/notification/log',
        component: 'view.notification_log',
        meta: {
          title: 'notification_log',
          i18nKey: 'route.notification_log'
        }
      },
      {
        name: 'notification_rule',
        path: '/notification/rule',
        component: 'view.notification_rule',
        meta: {
          title: 'notification_rule',
          i18nKey: 'route.notification_rule'
        }
      },
      {
        name: 'notification_template',
        path: '/notification/template',
        component: 'view.notification_template',
        meta: {
          title: 'notification_template',
          i18nKey: 'route.notification_template'
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user'
    },
    children: [
      {
        name: 'user_center',
        path: '/user/center',
        component: 'view.user_center',
        meta: {
          title: 'user_center',
          i18nKey: 'route.user_center'
        }
      }
    ]
  }
];
